In [1]:
import pandas as pd

C:\Users\ultra\AppData\Local\Temp\ipykernel_5844\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
ign = pd.read_csv('ign.csv', index_col='Unnamed: 0')
ign.drop(columns='url', inplace=True)
ign.head()

,score_phrase,title,platform,score,genre,editors_choice,release_year,release_month,release_day
0,Amazing,LittleBigPlanet PS Vita,PlayStation Vita,9.0,Platformer,Y,2012,9,12
1,Amazing,LittleBigPlanet PS Vita -- Marvel Super Hero E...,PlayStation Vita,9.0,Platformer,Y,2012,9,12
2,Great,Splice: Tree of Life,iPad,8.5,Puzzle,N,2012,9,12
3,Great,NHL 13,Xbox 360,8.5,Sports,N,2012,9,11
4,Great,NHL 13,PlayStation 3,8.5,Sports,N,2012,9,11

In [3]:
new_indexes = ign.index
new_indexes

Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,     9,
       ...
       18615, 18616, 18617, 18618, 18619, 18620, 18621, 18622, 18623, 18624],
      dtype='int64', length=18625)

In [4]:
ign.sort_values(by=['score', 'title'], ascending=[False, True], inplace=True)
ign.head()

,score_phrase,title,platform,score,genre,editors_choice,release_year,release_month,release_day
1408,Masterpiece,Checkered Flag,Lynx,10.0,Racing,N,1999,7,6
15757,Masterpiece,Chrono Trigger,Wii,10.0,"Action, RPG",Y,2011,5,25
3236,Masterpiece,Dragon Warrior III,Game Boy Color,10.0,RPG,Y,2001,7,20
10874,Masterpiece,Grand Theft Auto IV,Xbox 360,10.0,"Action, Adventure",Y,2008,4,25
10901,Masterpiece,Grand Theft Auto IV,PlayStation 3,10.0,"Action, Adventure",Y,2008,4,25

In [5]:
ign.index

Index([ 1408, 15757,  3236, 10874, 10901, 10836, 10838, 17163, 17164, 17998,
       ...
       13216,   439,   496, 16409, 16372,   574,  3074, 12513,   890,  5242],
      dtype='int64', length=18625)

In [6]:
result = ign[['title', 'score', 'score_phrase', 'platform', 'genre', 'release_year', 'release_month', 'release_day']]
result.index = new_indexes
result.head()

,title,score,score_phrase,platform,genre,release_year,release_month,release_day
0,Checkered Flag,10.0,Masterpiece,Lynx,Racing,1999,7,6
1,Chrono Trigger,10.0,Masterpiece,Wii,"Action, RPG",2011,5,25
2,Dragon Warrior III,10.0,Masterpiece,Game Boy Color,RPG,2001,7,20
3,Grand Theft Auto IV,10.0,Masterpiece,Xbox 360,"Action, Adventure",2008,4,25
4,Grand Theft Auto IV,10.0,Masterpiece,PlayStation 3,"Action, Adventure",2008,4,25

In [7]:
result.to_csv(path_or_buf='IGN games from best to worst.csv', index=False, sep=',')

In [8]:
pd.read_csv('IGN games from best to worst.csv').head()

,title,score,score_phrase,platform,genre,release_year,release_month,release_day
0,Checkered Flag,10.0,Masterpiece,Lynx,Racing,1999,7,6
1,Chrono Trigger,10.0,Masterpiece,Wii,"Action, RPG",2011,5,25
2,Dragon Warrior III,10.0,Masterpiece,Game Boy Color,RPG,2001,7,20
3,Grand Theft Auto IV,10.0,Masterpiece,Xbox 360,"Action, Adventure",2008,4,25
4,Grand Theft Auto IV,10.0,Masterpiece,PlayStation 3,"Action, Adventure",2008,4,25